SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER  FUNCTION [{schema}].[{functionName}](@urn as nvarchar(2048)) RETURNS BIT AS
BEGIN
    RETURN CASE WHEN @urn LIKE 'urn:%' THEN 1 ELSE 0 END
END
GO
